# Generated by Django 4.2.6 on 2023-10-27 22:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ninusStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default='Jackets and Tops', on_delete=django.db.models.deletion.CASCADE, to='ninusStore.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.ForeignKey(default='All Products', on_delete=django.db.models.deletion.CASCADE, to='ninusStore.wishlist'),
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 28, 9, 38, 32, 975199))),
                ('cart_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('product_size', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('product_img_url', models.CharField(max_length=2000)),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ninusStore.usercart')),
            ],
        ),
    ]
