# Generated by Django 4.2.6 on 2023-10-28 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninusStore', '0003_remove_cart_user_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='cart_date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 13, 8, 34, 211424)),
        ),
    ]
