# Generated by Django 4.2.6 on 2023-10-28 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninusStore', '0004_cart_product_price_alter_usercart_cart_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cart_date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 23, 32, 48, 738760)),
        ),
    ]
