# Generated by Django 4.2.6 on 2023-10-28 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninusStore', '0005_alter_usercart_cart_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ninusStore.order'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='cart_date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 0, 36, 21, 793871)),
        ),
    ]
