# Generated by Django 4.2.6 on 2023-10-30 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninusStore', '0010_remove_cart_order_order_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_price_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='cart_date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 0, 2, 31, 533307)),
        ),
    ]
