# Generated by Django 4.2.6 on 2023-10-31 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninusStore', '0011_cart_product_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cart_date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 0, 38, 53, 817928)),
        ),
    ]
